### ISSUE TITLE
Feature Request: Fold page embeds

### ISSUE THREAD

**Issue by ksqsf** [sethyuan/logseq-plugin-another-embed#1]
Example:

<img width="230" alt="圖片" src="https://user-images.githubusercontent.com/23358293/206467548-167cdee6-5174-436c-aabc-f6b3b5800845.png">

I cannot fold this embed to one line. It would be great if Another Embed supports this. Thanks!

**Comment by sethyuan** [comment]
嵌入页面或块的行为仍然由Logseq提供，插件不太好实现这个功能。但你可以变通地用 Alternative embed children 命令，类似这样：

```
- PlusCal
  - 此处alternative embed children PlusCal
```
