### ISSUE TITLE
没懂树形“收藏”与“最近使用”

### ISSUE THREAD

**Issue by karlz97** [sethyuan/logseq-plugin-another-embed#10]
很棒的插件，一直想实现这个功能！logseq原生的reference样式实在是别扭。
> 基于 namespace 或者 tagged pages 实现树形“收藏”与“最近使用”。可通过fixed页面属性来调整展示顺序，例如 fixed:: 100，数值越小位置越靠前。

请问可以用图片或者动图演示一下吗?没懂这个功能，谢谢！

**Comment by sethyuan** [comment]
树形收藏这块文档确实不够完善，抽空我补个演示视频。

**Comment by sethyuan** [comment]
演示做好了，README里第三个视频，hierarchical_favorites这个。

**Comment by karlz97** [comment]
明白了！太强大了
