### ISSUE TITLE
Collapsible embeds

### ISSUE THREAD

**Issue by ThinkSalat** [sethyuan/logseq-plugin-another-embed#12]
Hello,

I love this plugin! The page/block embeds are so much more useable now. I would really like to be able to collapse a a page embed. Currently, if I want to minimize the display of embedded pages, I need to indent them into a child block so I can collapse the parent. This adds more indentation and kind of squishes the content.

Ideally, I'd like to be able to collapse a page embed so it looks the same way a collapsed block embed looks. See my screenshots below to see what I mean

Block embed and page embed, both expanded
![image](https://github.com/sethyuan/logseq-plugin-another-embed/assets/31082405/e7993442-1ce8-42d8-9099-09c723d4dda0)

block embed collapsed
![image](https://github.com/sethyuan/logseq-plugin-another-embed/assets/31082405/6d003c69-7528-41eb-8983-f19494cd8845)

I appreciate your work, thank you!

**Comment by sethyuan** [comment]
@ThinkSalat It's implemented, please have a try.

**Comment by ThinkSalat** [comment]
It's perfect! Amazing, thank you so much :)
