### ISSUE TITLE
Table column drag, arrows

### ISSUE THREAD

**Issue by DutchPete** [sethyuan/logseq-plugin-another-embed#13]
Table columns: drag to change width does not work for me.

I have enabled show arrows when hovered: which arrows are meant?

**Comment by sethyuan** [comment]
Watch the last demo on the README, it demonstrates how to use this feature.

**Comment by DutchPete** [comment]
The last demo is about the tables. I still could not get it to work, until I found by trial and error that it only works for a basic table. For example, if there is this above the table:

```
logseq.table.version:: 2
logseq.table.borders:: true
logseq.table.hover:: cell
logseq.color:: plum
logseq.table.stripes:: true
```
it does not work, even though these are built-in Logseq properties.

Also the table does not work if there are inline HTML elements, such as e.g.
`<span style="color:limegreen">text</span>`.

**Comment by DutchPete** [comment]
Regarding the arrows, I still don't see which arrows are meant.

**Comment by sethyuan** [comment]
Yeah, v2 tables are not supported. I mentioned it in Discord but forgot to write it down in the README.

Inline HTML should be fine, I ran a basic test with the HTML you gave with a markdown table and it worked fine. What does your table look like?

The `hoverArrow` setting is a setting for hierarchical favorites, it's unrelated to tables. You can watch the 2nd demo for a grasp of the hierarchical favortes concept.

**Comment by sethyuan** [comment]
Bitcoins are illegal where I live. 😭 I'm using Buy me a Coffee for now, but recently I'm considering to move to Ko-Fi, heard it's easier to use.
