### ISSUE TITLE
路径面包屑的latex支持

### ISSUE THREAD

**Issue by YiZhiRikka** [sethyuan/logseq-plugin-another-embed#14]
不能正确渲染latex
![image](https://github.com/sethyuan/logseq-plugin-another-embed/assets/37006532/85c448fe-b4ae-49b8-808a-c8350c3b1488)

**Comment by sethyuan** [comment]
已经解决了，可尝试下新版本。

**Comment by YiZhiRikka** [comment]
> 已经解决了，可尝试下新版本。

可以了！感谢
