### ISSUE TITLE
default fixed value for hierarchy order

### ISSUE THREAD

**Issue by arlomh** [sethyuan/logseq-plugin-another-embed#15]
Hi!

It would be great if notes without a specified "fixed" property value were set at 0 by default, so if I wanted to move a particular note to the end of a hierarchy, I could set the value as "1" (and "2" for the note I want displayed after, "3" for the next, etc.); instead of manually setting a "fixed" value for all notes in the hierarchy to create my desired order. All notes without a set value (0) would continue be ordered alphabetically/ascending numerically, as is now if there's more than one note with the same "fixed" value.

**Example:**
Say I have three notes: "a" (no specified fixed value), "b" (fixed:: 1)", "c" (fixed:: -1)
Current order: c, b, a
Proposed order: c, a, b

**More info on my use case:** 
I use the favourites tree structure feature to organize school notes. I like to sort them in order of first course unit/topic -> most recent, rather than alphabetically. To do this, I title each note with the unit number in the beginning. The issue I have run into is if a course has over 9 units, the 10th note is placed between 1 and 2, rather than at the end after 9:
<img width="250" alt="Screenshot 2023-08-03 at 7 31 56 AM" src="https://github.com/sethyuan/logseq-plugin-another-embed/assets/29103570/e4a9eccc-0ce5-4b96-befb-1b7b81753b3a">

Not related to this plugin, but I run into a similar issue using namespaces:
<img width="281" alt="Screenshot 2023-08-03 at 7 35 52 AM" src="https://github.com/sethyuan/logseq-plugin-another-embed/assets/29103570/ca223e11-a85f-4a97-b6be-a2db9ae2af73">

Adding the "fixed" property to all notes in the hierarchy can get a bit tedious, with this I would only need to manually set a value for notes after 9, which I typically only have one or two of. It's not _that_ big of an inconvenience, but this would be a nice enhancement feature!

I hope this makes sense, let me know if you need any clarification or if there's something I'm missing that could solve this. 
Thanks!

**Comment by sethyuan** [comment]
Wow, this is a very detailed description 👍 Let me think about it, I'll report back later.

**Comment by sethyuan** [comment]
@arlomh BTW, for your specific use case, it's recommended to rename your units like this: `U01` .. `U10`. This solves the ordering issue for all systems that do alphanumeric ordering.

**Comment by arlomh** [comment]
@sethyuan Thanks for the tip!

Perhaps adding a separate property type for moving a note to the bottom (`fixed-bottom`) would be more intuitive to users so positive numbers can be used as well.

`fixed` could be renamed to `fixed-top`, or used interchangeably (to not disrupt existing hierarchies with notes that use `fixed`).

**Comment by sethyuan** [comment]
I don't know, do you have any other use cases for fixing items to the bottom? I'm not sure it's worth doing it.
