### ISSUE TITLE
[Question] Toggle auto heading feature — where is it now?

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-another-embed#19]
Changelog says it is «duplicate functionality». But where is it now?

**Comment by sethyuan** [comment]
In the Long Form plugin. 😂 Implementation is different but the functionality is the same.

**Comment by stdword** [comment]
Well, just duplicated it to separate [plugin](https://github.com/stdword/logseq13-missing-commands).

**Comment by sethyuan** [comment]
👌🏻

**Comment by stdword** [comment]
Hello! The plugin is finally released! ❤️

**Comment by sethyuan** [comment]
> Hello! The plugin is finally released! ❤️

Congrats! 🎉
