### ISSUE TITLE
能否添加一个全局 “Alterative embed” 功能

### ISSUE THREAD

**Issue by msjsc001** [sethyuan/logseq-plugin-another-embed#2]
开发者你好，很喜欢你的这个插件。
默认logseq 的 block embed  会是“块中块”的效果（block embed 结构上就缩进一级）。这个插件的“Alterative embed”能让 “block embed ”是自为一级的显示，结构和视觉上都更合理，感觉软件默认就应该自带你这个插件功能，个人非常喜欢。

能否添加一个开启插件后全局 logseq 的 block embed 都按 “Alterative embed ” 方式显示的功能选项。我想（我不懂编程）这个“全局Alterative embed”功能或许从 CSS 上入手不使用 “[[.embed]]{{embed ((UUID))”  的方式，是不是更更能保持这个插件 logseq未来 更新后也保持长期稳定。

**Comment by sethyuan** [comment]
我考虑一下，没有问题的话我可以添加一个配置来开启全局的功能。

**Comment by sethyuan** [comment]
我加入了一个插件配置，开启即可开启全局embed。之前的命令也仍可以用，尤其embed children也还是很有用的。

**Comment by msjsc001** [comment]
> 我加入了一个插件配置，开启即可开启全局embed。之前的命令也仍可以用，尤其embed children也还是很有用的。
感谢，待会试一试！

**Comment by msjsc001** [comment]
效果非常好，关闭这个问题。
