### ISSUE TITLE
Last release change broke bullet alignment

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-another-embed#20]
Hello!
Why [this](https://github.com/sethyuan/logseq-plugin-another-embed/commit/10fa67a2ae276608856146fec408d814b972e446) change?

## Before:
<img width="150px" src="https://github.com/sethyuan/logseq-plugin-another-embed/assets/1984175/4004a348-da0d-4544-ba04-cd17ee5fbf09"/>

## After:
<img width="150px" src="https://github.com/sethyuan/logseq-plugin-another-embed/assets/1984175/f82de6fc-5fc1-4ddd-8bdc-575e10edf2ad"/>

Probably it is better to shift only header of embedded page?

**Comment by sethyuan** [comment]
Thanks for reporting, it's fixed now.
