### ISSUE TITLE
Query Table SHIFTED, when embed block inside

### ISSUE THREAD

**Issue by stdword** [sethyuan/logseq-plugin-another-embed#22]
Hello! Just found the funny bug:

<img width="800px" src="https://github.com/sethyuan/logseq-plugin-another-embed/assets/1984175/09f02243-175c-4a5d-a369-a7834f1efc11"/>

Expected that second query table also won't be shifted.

**Comment by sethyuan** [comment]
Fixed.

**Comment by stdword** [comment]
Checked! Very fast 🙏🙏
