### ISSUE TITLE
在块嵌入时，同时暴露面包屑

### ISSUE THREAD

**Issue by WsinGithub** [sethyuan/logseq-plugin-another-embed#3]
Seth 大佬好！来提个需求 :D

此需求来源于「主题阅读」时，在一个 page 里，用「块嵌入」手动汇总「不同信息源」对「同一主题」的解读。

目前看起来是这样，不太能立刻反应到出处：
![image](https://user-images.githubusercontent.com/55137994/219606116-d4471e8a-d873-4d25-93a4-b1aeefb94267.png)

希望实现：
![image](https://user-images.githubusercontent.com/55137994/219606259-5a4d5944-7c57-41fb-bd24-90ab82a360ea.png)

希望可以保留原生块嵌入缩进样式的同时，额外添加面包屑。

（当然后续结合一下就是 another embed 的去缩进样式+面包屑，但不希望只能这样~）

**Comment by sethyuan** [comment]
已实现。
