### ISSUE TITLE
shortcut error

### ISSUE THREAD

**Issue by lef-est** [sethyuan/logseq-plugin-another-embed#4]
![image](https://user-images.githubusercontent.com/9643637/221128074-2d825994-366f-4c2d-afd8-b7dca37bc239.png)

I get this after disabling and re-enabling the plugin.

**Comment by sethyuan** [comment]
Just ignore it. It's because Logseq does not have an API for unregistering shortcuts, nor it avoids displaying this error.

**Comment by lef-est** [comment]
Thanks! I'll close it then.
