### ISSUE TITLE
需求：树形“收藏”的支持手动拖拽排序

### ISSUE THREAD

**Issue by dale502** [sethyuan/logseq-plugin-another-embed#5]
可以在页面属性写入数据来持久化
<img width="547" alt="image" src="https://user-images.githubusercontent.com/69394230/225498704-46b11107-8c99-4ef7-b074-f84cc90e1d43.png">

**Comment by huanhuanqiongqiong** [comment]
namespace也用相同方法支持吧

**Comment by sethyuan** [comment]
已实现，虽然不是靠拖拽。
