### ISSUE TITLE
需求：隐藏全局模式缩进Embed的大黑边

### ISSUE THREAD

**Issue by fishpigbird** [sethyuan/logseq-plugin-another-embed#7]
因为既然全局模式下，无法像`[[.embed]]{{embed }}`**记住**embed的**缩进状态**，那么这个大黑边在全局模式其实就属于**冗余**。（注意到全局会覆盖掉` .embed`的状态。）

正常情况应该是这样：
全局模式下是否展示此黑边的选项。
- 若展示，则点击这个黑边会把普通`embed`转换成 ` .embed` 。以实现记住缩进状态。
- 若不显示，则不显示大黑边。

建议：
**就默认全局模式不显示就好啦**

![image](https://user-images.githubusercontent.com/128216091/232280544-7f2c82c4-5a6b-40ad-b923-9e08f90cc7cc.png)

**Comment by fishpigbird** [comment]
黑边好大T_T
![image](https://user-images.githubusercontent.com/128216091/232283627-469924f9-d1d6-4e7c-81e2-19cc07e5c834.png)

**Comment by sethyuan** [comment]
确实太显眼，我可以尝试把它调小点儿。不显示是不正确的，因为它就是用来切换标准显示和替代显示的。

**Comment by fishpigbird** [comment]
抱歉，大意了，确实不能删掉，在**拖动block**的时候确实需要切换一下。

**Comment by sethyuan** [comment]
@fishpigbird 我调整了这个控制条的显示逻辑，现在不会那么碍眼了。试试新版本。

**Comment by fishpigbird** [comment]
完美，感谢！
