### ISSUE TITLE
功能建议： 自定义embed子节点条目

### ISSUE THREAD

**Issue by fishpigbird** [sethyuan/logseq-plugin-another-embed#8]
embed子节点自定义
使用场景：子节点很多都是一个父节点的多个分类概念，但是很多时候我们可能只想嵌入父节点下的其中一个子节点。虽然可以直接通过。

![image](https://user-images.githubusercontent.com/128216091/232948526-d5dcf271-47e1-4f20-a03c-2d743853b050.png)

**Comment by sethyuan** [comment]
你这个场景建议使用 `/Alternative Embed Children`。
